version: "3.1"
services: 
  mysql_cursos:
    container_name: mysql_cursos
    hostname: mysql_cursos
    image:  mysql
    restart: always
    command: 
      - --mysql-native-password=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3354:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha

volumes:
  mysql_data: